server:
  port: 21066

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/app/db/cashbook-cloud.db
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schema/schema.sql

mybatis:
  mapper-locations: classpath:mybatis/**.xml
  configuration:
    map-underscore-to-camel-case: true

filePath: /app/data/

system:
  salt: dingdangdog