---
name: Bug👻反馈
description: 提交 Bug 反馈的模板
title: "[BUG] - {问题概述}"
labels: [bug]
---

感谢您提交 Bug 反馈！请务必填写以下信息，以便我们尽快定位和解决问题。

**问题概述:**

请简要描述您遇到的问题。

**复现步骤:**

请详细描述如何复现问题，包括操作步骤、截图或录屏等。

**预期结果:**

请描述您期望的正确行为。

**实际结果:**

请描述您实际遇到的错误行为。

**截图/录屏:**

请附上截图或录屏，以便我们更直观地了解问题。

**环境信息:**

- 安装操作系统:
- 浏览器版本:
- 软件版本:
- 其他相关信息:

**日志信息:**

请附上错误日志信息，帮助我们定位问题。
