name: "Bug👻反馈"
description: 提交 Bug 反馈
title: "[BUG]: "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: 问题概述
      description: 请简要描述您遇到的问题。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 环境信息
      description: 请提供以下环境信息：
      value: |
        - 服务器操作系统:
        - Cashbook部署方式:
        - Cashbook版本:
        - 浏览器版本:
        - 其他相关信息:
    validations:
      required: true

  - type: textarea
    attributes:
      label: 截图/录屏/日志
      description: 请附上截图、录屏或错误日志信息，以便我们更直观地了解问题。
      value: |
        **截图/录屏**:
          
        **日志**:

  - type: textarea
    attributes:
      label: 复现步骤/预期结果/实际结果
      description: 请详细描述如何复现问题，包括操作步骤、截图或录屏等。
      value: |
        **复现步骤**:

        **预期结果**:

        **实际结果**:
