---
name: 功能❤️建议
description: 提交功能建议的模板
title: "[功能建议] - {建议概述}"
labels: [enhancement]
---

感谢您提出功能建议！请详细描述您的建议，并说明理由。

**建议概述:**

请简要描述您的功能建议。

**详细描述:**

请详细描述您希望添加的功能，包括具体用法、界面设计等。

**理由:**

请说明您提出此建议的理由，以及该功能可能带来的好处。

**其他说明:**

如果您有其他需要补充说明的内容，请在此处填写。
