name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "打包Docker"
        required: true
        type: choice
        options:
          - WEB

jobs:
  build:
    environment: docker_hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t dingdangdog/cashbook:3.0.1_BETA -t dingdangdog/cashbook:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push dingdangdog/cashbook:3.0.1_BETA
          docker push dingdangdog/cashbook:latest

      - name: Clean up Docker images
        run: docker system prune -af
